{% set name = "nputop" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/youyve/nputop/archive/v{{ version }}.tar.gz
  sha256: c0650244af08d5006936738147f900c5de653cccd0972199306fd372f8e5b1d2

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - nputop = nputop.cli:main
  skip: True  # [win or osx]

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - psutil >=5.6.6
    - cachetools >=1.0.1
    - termcolor >=1.0.0

test:
  imports:
    - nputop
  commands:
    - nputop --version || echo "Skipping hardware-dependent test"

about:
  home: https://github.com/youyve/nputop
  license: Apache-2.0
  license_file: LICENSE
  summary: 'nputop: Interactive Ascend-NPU Process Viewer'
  description: |
    nputop is an interactive process viewer for Ascend-NPU, providing real-time monitoring of NPU metrics and processes.
    Note: Currently supports Linux only. Requires manual installation of Ascend-NPU drivers (see project documentation).
  doc_url: https://github.com/youyve/nputop
  dev_url: https://github.com/youyve/nputop

extra:
  recipe-maintainers:
    - youyve
